name = "vOptGeneric"
uuid = "d80f1e47-7c1f-50ef-848d-735630893f00"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Combinatorics = "≥ 0.7.0"
JuMP = "≥ 0.19.0"
julia = "≥ 1.0.0"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test", "Cbc", "JuMP"]
